### ISSUE TITLE
Multiple accounts and taxes

### ISSUE THREAD

**Issue by Slinky142** [cloudnode-pro/BankAccounts#107]
Hi, I might have a few suggestions for the plugin, but I don't know whether it already exists or not. If so, please say that you can perhaps create several accounts, but they cost money, so the first account is free and off The second is that the money costs and the price can be set in the config and that as the owner I have a company account and players always have to send a certain amount from their account to a certain account at the beginning of the month, which happens automatically You can also edit it in the config. I hope you can do it, but it's still a great plugin

**Comment by zefir-git** [comment]
Hi! There is an interest payment functionality which automatically adds or removes a percentage on a fixed interval.

Here is the config for that:
https://github.com/cloudnode-pro/BankAccounts/blob/fb29e397e980c80a791810982bec97574c9a97e9/src/main/resources/config.yml#L230-L256

To use the interest functionality, the server account needs to be enabled:
https://github.com/cloudnode-pro/BankAccounts/blob/fb29e397e980c80a791810982bec97574c9a97e9/src/main/resources/config.yml#L56-L60

More info on interest payments:
 - #69

Setting the interest percentage to a negative number will make it act as a fee. A flat/fixed fee was not implemented, because, unlike a percentage, it can lead to negative balances. With the current functionality, you won't be able to disable it on a per-account basis (e.g. for the first account). However, you could for example only enable it for business accounts. Could this work for your server?

**Comment by Slinky142** [comment]
okay and what about the multiple accounts? And I don't understand the interest thing, so I just want players to always get certain percentages on a certain account at the beginning of the month, which you can set. I just don't understand how this is regulated with the plugin

**Comment by zefir-git** [comment]
What about the multiple accounts?

The interest adds or removes to/from all accounts at a specified time. For example, to take 5% of all business accounts at the start of every month, you can use something like this:

```yml
interest:
     # Personal accounts
     0:
         rate: 0 # 0% means interest rate is not enabled
         interval: 1440
         description: "Interest payment (<rate-formatted>)"
     # Business accounts
     1:
         rate: -5 # -5% (5% is removed from the accounts)
         interval: 43800 # every month (43800 minutes in a month)
         description: "Interest payment (<rate-formatted>)"
```

With this config, 5% will be removed from all business accounts approximately every 30 days.
